# Generated by Django 3.2 on 2021-04-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
